repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=88]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--profile=black, --line-length=88]
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: sed -i '' 's/[[:space:]]*$//'
        language: system
        types: [text]
      - id: end-of-file-fixer
        name: Fix End of Files
        entry: bash -c 'for file in "$@"; do if [[ -s "$file" && ! -z "$(tail -c 1 "$file")" ]]; then echo >> "$file"; fi; done' --
        language: system
        types: [text]
